@echo off
REM ============================================================================
REM  2-stream-to-simhub.bat
REM  Run this on the GAMING PC (the machine that runs Wreckfest 1).
REM  It streams telemetry over UDP to the SimHub PC at 192.168.50.2:22123.
REM
REM  NOTE: the SimHub External Sim packet is not wired yet (it needs the struct
REM  generated by SimHub's "Copy demo code" button for wreckfest.simdef). Until
REM  then this sends the documented native packet. Use 1-verify-console.bat
REM  first to confirm real data is being read.
REM
REM  Edit the IP/port below if your SimHub PC differs.
REM  Reading game memory needs Administrator rights; this self-elevates.
REM ============================================================================

set TARGET=192.168.50.2:22123

REM --- self-elevate if not already admin ---
net session >nul 2>&1
if %errorlevel% neq 0 (
    powershell -Command "Start-Process -FilePath '%~f0' -Verb RunAs"
    exit /b
)

cd /d "%~dp0"
echo Streaming wreckfest-teleport telemetry to %TARGET% ...
echo Press Ctrl+C to stop.
echo.
wreckfest-teleport.exe udp --target %TARGET% --rate 100

echo.
echo wreckfest-teleport stopped.
pause
